[project]
name = "flightplan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
    "pygeomag>=1.1.0",
    "setuptools>=75.8.0",
    "xmltodict>=0.14.2",
]

[tool.ruff]
format.quote-style = "double"
format.docstring-code-format = true


[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.6",
]
